Repository RegioHelden/django-languageselect, pull requests merged in 2025-04, with the labels that each got.

#17 Add support for Django 5.1 and 5.2, remove support for Django 5.0 and Python 3.10
  .github/workflows/workflow.yml
  pyproject.toml
Labels: backwards-incompatible

#18 Release v6.0.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#19 Pin reusable workflow release
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yml
Labels: skip-changelog

#20 Move project version to standalone file
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yml
  pyproject.toml
  version
Labels: skip-changelog

#21 Preparations for modulesync rollout
  .sync.yml
  Dockerfile
  compose.yaml
  system_dependencies.txt
Labels: infrastucture

#22 Updates from modulesync
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .gitignore
  .vscode/tasks.json
  Dockerfile
  LICENSE
  compose.yaml
  example/__init__.py
  manage.py
  pyproject.toml
Labels: infrastucture

#24 Updates from modulesync
  .github/dependabot.yml
Labels: infrastucture

#25 Updates from modulesync
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#26 Updates from modulesync
  .devcontainer/devcontainer.json
Labels: infrastucture

#27 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#28 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  Dockerfile
Labels: infrastucture

#30 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture
